### ISSUE TITLE
cv2.error: OpenCV(4.5.4-dev) /tmp/pip-req-build-h45n7_hz/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'  

### ISSUE THREAD

**Issue by TrieuLe0801** [ehanhalici/digital-number-ocr#1]
I got this error with cv2:
`cv2.error: OpenCV(4.5.4-dev) /tmp/pip-req-build-h45n7_hz/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'?`
Do you have any idea with this?

**Comment by ehanhalici** [comment]
i am not sure but i found this,

(https://www.codegrepper.com/code-examples/whatever/error:+(-215:Assertion+failed)+!_src.empty()+in+function+'cv::cvtColor')

maybe, cv2.VideoCapture() can't find where the camera is and hence gives src.empty() since None is returned instead of image or video. Can you check your camera.

you can try this in use.py, line 5
cap = cv2.VideoCapture(1)
